apiVersion: v1
kind: Pod
metadata:
  name: pod-hostpath
  namespace: restricted-ns
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: myvolume
      mountPath: /data
  volumes:
  - name: myvolume
    hostPath:
      path: /data