apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: tp-kubernetes
spec:
  type: ClusterIP
  selector:
    app: tp-postgres
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: port-postgres
  
