apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:     
      - name: mongo
        image: mongo:4.0  
        ports:
          - containerPort: 27017
        resources:
          limits:
            cpu: "200m"
            memory: "256Mi"

--- 

apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    app: db
  type: ClusterIP
  ports:
  - port: 27017

---

apiVersion: batch/v1
kind: Job
metadata:
  name: mongo-dump
spec:
  template:
    spec:
      containers:
      - name: mongodump
        image: mongo:4.0
        command: ["sh", "-c", "mongodump", "--host", "db", "--archive=/tmp/db.gz"]
        resources:
          limits:
            cpu: "200m"
            memory: "256Mi"
      restartPolicy: Never