apiVersion: v1
kind: PersistentVolume
metadata:
  name: tp-volume
  namespace: tp-kubernetes
  labels:
    storage: good-one
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: /data-tp
    type: DirectoryOrCreate