apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: client1
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx:latest
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: "200m"
        memory: "128Mi"
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    
