apiVersion: v1
kind: ConfigMap
metadata:
  name: mon-configmap
data:
  param1: valeur1
  param2: valeur2


---

apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
  - name: myapp
    image: alpine:3.15
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    env:
      - name: PARAM1
        valueFrom:
          configMapKeyRef:
            name: mon-configmap
            key: param1

---

apiVersion: v1
kind: Pod
metadata:
  name: myapp-2
  labels:
    name: myapp-2
spec:
  containers:
  - name: myapp-2
    image: alpine:3.15
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
      - name: config-volume
        mountPath: /
  volumes:
  - name: config-volume
    configMap:
      name: conf-map